plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    alias(libs.plugins.userdev)
}

tasks.named('wrapper', Wrapper).configure {
    // Define wrapper values here so as to not have to always do so when updating gradlew.properties.
    // Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
    // documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
    // file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
    // (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
    distributionType = Wrapper.DistributionType.BIN
}
var minecraft_version = libs.versions.minecraft.get()
var minecraft_version_range = libs.versions.minecraftRange.get()
var neo_version = libs.versions.neoforge.get()
var neo_version_range = libs.versions.neoforgeRange.get()
var loader_version_range = libs.versions.loaderRange.get()

group = mod_group_id
version = "${minecraft_version}-" + mod_version

libsDirName = "../output"
distsDirName = "../output"

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)


minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')

runs {

    configureEach {

        systemProperty 'forge.logging.markers', 'REGISTRIES'

        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {

        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id

    }

    server {

        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'

    }

    gameTestServer {

        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id

    }

    data {

        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "voltaic:Voltaic:1.21.1-1.0.1-1"
    implementation libs.neo.neoforge
    compileOnly libs.bundles.jeiApi
    localRuntime libs.jei
    compileOnly libs.mekanism
    //localRuntime libs.mekanism
   
}

tasks.register('sourcesJar', Jar).configure {
    dependsOn classes
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
}

tasks.register('deobfJar', Jar).configure {
    from sourceSets.main.output
    archiveClassifier = 'deobf'
}

tasks.named('publish').configure {
    dependsOn 'reobfJar'
}


tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_credits            : mod_credits,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

artifacts {
    archives sourcesJar
    archives deobfJar
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
java {
  withSourcesJar()   // <- generates sources JAR
}
repositories {
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}